include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    curly_braces_in_flow_control_structures: false
    use_build_context_synchronously: false